### ISSUE TITLE
The import org.tensorflow.framework cannot be resolved

### ISSUE THREAD

**Issue by xiaoyesoso** [FlinkML/flink-tensorflow#15]
I compiled FTF lib and examples，and  imported lib into examples project.However , eclipse showed “The import org.tensorflow.framework cannot be resolved.object framework is not a member of package org.tensorflow.” exp:
```java
import org.tensorflow.framework.{SignatureDef, TensorInfo}
```
and I also could not find  `org.tensorflow.framework`

                                                                                     Thanks

**Comment by EronWright** [comment]
@xiaoyesoso recently (see #12) we took a dependency on a library of proto classes ([ref](https://search.maven.org/#artifactdetails%7Corg.tensorflow%7Cproto%7C1.1.0%7Cjar)) provided by TensorFlow.   Maybe you need to re-import the project into Eclipse?

**Comment by EronWright** [comment]
@xiaoyesoso do you have an update as to whether you solved the issue?   Willing to help.

**Comment by xiaoyesoso** [comment]
@EronWright Sorry,I was busy,and it perfectly works.
