### ISSUE TITLE
Maven Dependency flink-tensorflow_2.11 not found

### ISSUE THREAD

**Issue by chandanparihar1986** [FlinkML/flink-tensorflow#21]
Can you please help me to get the maven dependency for flink-tensorflow_2.11? I could not find the dependency with this name in any repository.

**Comment by EronWright** [comment]
The library is not published to Maven Central yet, but you can build it yourself.  Please follow the instructions [on the wiki](https://github.com/FlinkML/flink-tensorflow/wiki/Building), thanks!
