### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by cula** [FlinkML/flink-tensorflow#22]
I can't find any flink-tensorflow-related jar in maven repo。
I'd like to use tensorflow-trained model in flink. Could help me to install this? 

ps: The doc should be enhanced

**Comment by karmen-chan** [comment]
Have you find the right way to use tensorflow-trained model on flink? I am dealing with the same issue, and maybe we can figure it out together? @cula

**Comment by EronWright** [comment]
Hi, I am happy to help with this.  Let me send you some instructions
tomorrow.

**Comment by karmen-chan** [comment]
Thanks so much！ @EronWright

**Comment by wweichn** [comment]
I also can't find how to install flink_tensorflow with pip on Mac.
Anyone can help?

**Comment by karmen-chan** [comment]
@wweichn Since it's a scala project, you can open it with eclipse on Mac. BTW, I think pip is most used for installation of python libraries. You can use mvn install to start the project.
